// Barrel export for all services
export { projectsService } from './projects.service';
export { tasksService } from './tasks.service';
export { issuesService } from './issues.service';
export { authService } from './auth.service';
export { organizationsService } from './organizations.service';
export { milestonesService } from './milestones.service';
export { modulesService } from './modules.service';
export { activitiesService } from './activities.service';
export { teamService } from './team.service';
export { dashboardService } from './dashboard.service';
export { apiClient } from './api/client';
export { API_ENDPOINTS } from './api/endpoints';
